config/routes.rb
Rails.application.routes.draw do
  resources :trips
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  validates :duracion, numericality: {greater_than: 0, allow_nil: false}
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to trips_url
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
  @trip = current_user.trips.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit, alert: "Lo siento, corrija por favor"
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path, notice: "Viaje eliminado"
  end

  private
  def trip_params
    params.require(:trip).permit(:nombre, :descripcion, :tarifa, :duracion, :imagen, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.erb
<style media="screen">
h1{
  color: #F96009;
  font-family: "Arial";
  font-weight: "600";
  font-size: 20px;
}
p{
  text-align: justify;
  color: #101435;
  font-family: "Arial";
  font-weight: "500";
  font-size: 14px;
}
.padding-b{
  padding-bottom: 30px;
}
</style>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-sm-12 col-md-12 col-lg-4 padding-b">
      <img src="/assets/ecorutas.png" width=100%>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-8">
      <h1>Rutas turísticas por Colombia</h1>
      <p>Bienvenidos a EcoTrip, una plataforma para ver,
        vivir y disfrutar del turismo rural ambiental en Colombia.</p>
        <p>Registrate como Guia o trotamundos, para acceder a todas las rutas.</p>

      <p>Viajes: Las rutas vinculadas están verificadas, también puedes acceder
      a las páginas oficiales turísticas nacionales, para que puedas tener
      la certeza y confianza para iniciar tu travesía por nuestro maravilloso
      país.</p>
      <p>Colombia es uno de los países con mayor biodiversidad de flora y fauna,
      con grandes parques nacionales naturales, albergando en su territorio la
      mayor extensión de páramo del mundo, a más de 3.000 especies de mariposas
      y a un 20% del total de las especies de aves del planeta. Todo esto se
      extiende en su amplio territorio, que cuenta con hermosos paisajes,
      debido a que tiene costas en los dos océanos y es atravesado por la
      Cordillera de los Andes.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecotrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style media="screen">
      .orange-line{
        border: 2px solid #F96009;
        width: 50%;
        margin-top: 0px;
        padding-bottom: 0px;
       }
       .text-footer{
         text-align: center;
         color: #555555;
         font-family: "Arial";
         font-weight: "500";
         font-size: 12px;
         margin-top: -10px;
         margin-bottom: 0px;
       }
       h4{
         color: white;
         font-family: "Arial";
         font-weight: "500";
         font-size: 12px;
       }
    </style>
  </head>

  <body>
    <div class="container-fluid" style="padding-bottom: 15px;">
      <div class="row align-items-end">
        <div class="col-1">
          <img src="/assets/Logo-ecotrip.png" style="padding-left: 20px;" width="100px">
        </div>
        <div class="col-11">
          <img class="align-bottom" src="/assets/Slogan-ecot.png" width=800px>
        </div>
      </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #AECD13; margin-bottom: 30px;">
  <strong><%= link_to "INICIO", root_path, class:"navbar-brand", style:"color: white;" %></strong>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a><%= link_to "Crear viaje", "/trips/new", class:"btn btn-light" %></a>
      </li>
    </ul>

    <div>
      <% if user_signed_in? %>
       <%= link_to current_user.email, edit_user_registration_path, style:"color:white; text-decoration: none;" %>
       <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class:"btn btn-outline-light" %>
      <% else %>
       <%= link_to "Registrate", new_user_registration_path, class:"btn btn-outline-light" %>
       <%= link_to "Inicia Sesion", new_user_session_path, class:"btn btn-outline-light" %>
      <% end %>
    </div>
  </div>
</nav>

    <%= yield %>

  </body>
  <!-- Footer -->
  <footer class="page-footer", style="position:relative; margin-top: 50px; auto; bottom:0; width:100%;">

    <!-- Copyright -->
    <div class="footer-copyright text-center">
      <hr class="orange-line">
      <p class="text-footer">COLOMBIA PÁGINAS OFICIALES</p>
    </div>
    <div class="footer-logos" style="background-color: #AECD13;">
      <div class="container" style="padding: 20px 0px;">
        <div class="row">
          <div class="col-sm-1 col-md-3 col-lg-3">
            <div class="row">
              <div class="col-4">
                <img src="/assets/Logo-parquesNacionales.png" height="80px">
              </div>
              <div class="col-8" style="vertical-align: middle;">
                <h4 style="padding-top: 30px;">PARQUES NACIONALES</h4>
              </div>
            </div>
          </div>
          <div class="col-sm-1 col-md-3 col-lg-3">
          </div>
          <div class="col-sm-1 col-md-3 col-lg-3">
            <div class="row">
              <div class="col-4">
                <img src="/assets/Logo-proco.png" height="80px">
              </div>
              <div class="col-8">
                <h4 style="padding-top: 30px;">PROCOLOMBIA</h4>
              </div>
            </div>
          </div>
          <div class="col-sm-1 col-md-3 col-lg-3">
          </div>
        </div>
      </div>

    </div>




    <!-- Copyright -->

  </footer>
  <!-- Footer -->
</html>

app/views/trips/edit.html.erb
<h1>Trips#edit</h1>
<p>Find me in app/views/trips/edit.html.erb</p>

app/views/trips/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6">
      <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <% Trip.all.each_with_index do |v,i| %>
            <li data-target="#carouselExampleCaptions" data-slide-to="<% i+1 %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="https://asset1.zankyou.com/images/mag-post/e01/ae53/685//-/co/wp-content/uploads/2017/05/Valle-del-cocora-Watch_The_World.jpg"
              class="d-block w-100" alt="...">
              <div class="carousel-caption d-none d-md-block">
                <h1>VIAJES</h1>
                <br>
                </div>
            </div>
            <% Trip.all.each do |v| %>
            <div class="carousel-item">
              <%= image_tag(v.images[0], class:"d-block w-100") %>
              <div class="carousel-caption d-none d-md-block">
                <h3><%= v.nombre %></h3>
                <h4><%=link_to 'Ver viaje', "/trips/#{v.id}", class:"btn btn-light"%></h4>
              </div>
            </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Siguiente</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
<% if user_signed_in? && current_user.guia %>
<div class=container style=>
<div class="row justify-content-md-center">
<div class="col-4">
<h1 class="text-center">Nuevo viaje</h1>
<hr>
<center>
<%= form_for @trip do |f| %>
  <%= f.label :nombre %><br />
  <%= f.text_field :nombre %><br />

  <%= f.label :descripcion %><br />
  <%= f.text_area :descripcion %><br />

  <%= f.label :tarifa %><br />
  <%= f.number_field :tarifa, style:"width: 100px"%> COP<br />

  <%= f.label :duracion %><br />
  <%= f.number_field :duracion, style:"width: 100px" %> Mins<br />

  <%= f.label :imagen %><br />
  <%= f.file_field :images, multiple: true %><br /><br />

  <%= f.submit %>
<% end %>
</center>
</div>
</div>
</div>
<% else %>
<div class="container">
<div class="row justify-content-md-center">
<div class="col-6">
  <img src="/assets/LOGO1.png" width= 100%>
</div>
</div>
</div>
<% end %>

app/views/trips/show.html.erb
<style>
  .imagenes{
    width: 300px;
  }
</style>
<div class="container">
<p>
  <strong>Nombre:</strong>
  <%= @trip.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @trip.descripcion %>
</p>

<p>
  <strong>Tarifa:</strong>
  <%= @trip.tarifa %> COP
</p>

<p>
  <strong>Duracion:</strong>
  <%= @trip.duracion %> mins
</p>

<% @trip.images.each do |i| %>
<%= image_tag(i, class:"imagenes") %>
<% end %>
<br><br>

<% if current_user.email == @trip.user.email %>
<%= link_to 'Editar', edit_trip_path(@trip) %> |
<%= link_to 'Borrar', trips_path, method: :delete %> |
<% else %>
<%= link_to 'Contactar guia' %> |
<% end %>
<%= link_to 'Voler',trips_path %>
</div>